var staticDataSource =
{
    regions: [
        "CA",
        "NY",
        "FL",
        "TX",
        "PA",
        "IL",
        "OH",
        "MA",
        "MI",
        "WA",
        "NC",
        "NJ",
        "GA",
        "MD",
        "VA",
        "WI",
        "CO",
        "MN",
        "TN",
        "AZ",
        "MO",
        "OR",
        "IN",
        "CT",
        "OK",
        "KY",
        "SC",
        "LA",
        "AR",
        "AL",
        "NM",
        "KS",
        "UT",
        "NV",
        "IA",
        "DC",
        "ME",
        "MS",
        "NE",
        "NH",
        "WV",
        "HI",
        "RI",
        "ID",
        "DE",
        "AK",
        "MT",
        "PR",
        "ND",
        "SD"
    ],
    insurances: [
        "CIGNA",
        "AETNA",
        "UNITEDHEALTHCARE",
        "HUMANA",
        "BLUE CROSS AND BLUE SHIELD",
        "MULTIPLAN",
        "BLUE CROSS BLUE SHIELD",
        "COVENTRY HEALTH CARE",
        "MEDICAID",
        "MEDICARE",
        "PHCS",
        "GREAT WEST HEALTHCARE",
        "WELLPOINT",
        "FIRST HEALTH NETWORK",
        "HEALTHNET",
        "GUARDIAN",
        "DELTA DENTAL",
        "MET-LIFE",
        "UNITED CONCORDIA",
        "AMERITAS",
        "UNICARE",
        "UNITEDHEALTHCARE DENTAL",
        "GHI",
        "OXFORD HEALTH PLANS",
        "ASSURANT HEALTH",
        "DENTEMAX DENTAL",
        "ANTHEM",
        "PACIFICARE",
        "RAILROAD MEDICARE",
        "COVENTRY HEALTHCARE",
        "MEDICAL MUTUAL OF OHIO",
        "WELLCARE",
        "PRINCIPAL FINANCIAL",
        "GREAT-WEST HEALTHCARE",
        "AMERIGROUP",
        "WORKERS' COMPENSATION",
        "BLUE CROSS - CALIFORNIA",
        "KAISER PERMANENTE",
        "WELLCARE HEALTH PLANS",
        "BCBS",
        "OXFORD",
        "PPOM",
        "MOLINA",
        "THE GUARDIAN LIFE INSURANCE COMPANY - AMERICA",
        "PACIFICSOURCE",
        "SAGAMORE HEALTH NETWORK",
        "CENTENE",
        "FIRST CHOICE HEALTH",
        "PROVIDENCE HEALTH PLANS",
        "EVERCARE"
    ],
    localities: [
        "NEW YORK",
        "BROOKLYN",
        "CHICAGO",
        "LOS ANGELES",
        "HOUSTON",
        "PHILADELPHIA",
        "PORTLAND",
        "WASHINGTON",
        "BOSTON",
        "SAN FRANCISCO",
        "SAN DIEGO",
        "SEATTLE",
        "ROCHESTER",
        "DALLAS",
        "BRONX",
        "BALTIMORE",
        "SAINT LOUIS",
        "COLUMBUS",
        "PHOENIX",
        "MINNEAPOLIS",
        "PITTSBURGH",
        "CLEVELAND",
        "SAN ANTONIO",
        "MIAMI",
        "ATLANTA",
        "INDIANAPOLIS",
        "LAS VEGAS",
        "SPRINGFIELD",
        "SACRAMENTO",
        "DENVER",
        "MILWAUKEE",
        "CINCINNATI",
        "ALBUQUERQUE",
        "OKLAHOMA CITY",
        "LOUISVILLE",
        "TAMPA",
        "JACKSONVILLE",
        "AUSTIN",
        "SALT LAKE CITY",
        "NASHVILLE",
        "COLUMBIA",
        "TUCSON",
        "BUFFALO",
        "DETROIT",
        "CHARLOTTE",
        "RICHMOND",
        "MADISON",
        "KANSAS CITY",
        "ORLANDO",
        "OAKLAND"
    ]
};